### PR TITLE
update API and image URI

### LINKED ISSUE #2: CryptoCompare API closed
They recommend to use https://min-api.cryptocompare.com/ but no Image inside :(

https://www.cryptocompare.com/api/#
> DUE TO ABUSIVE USAGE, IF YOU WANT YOUR CLIENTS TO DIRECTLY USE OUR APIS, USE THE MIN-API PATH. (THE HEADER Access-Control-Allow-Origin: * is only set on min-api paths)

### PR DESCRIPTION
**Pull request by purplematter**
fix #2

### CODE REVIEW

**Comment by rdegges** [comment]
Thanks! This is awesome.

**Comment by giodelgado** [comment]
Seems like it isn't working again :(

**Comment by rdegges** [comment]
Ugh... Another issue with a free API provider? Anyone got another to use?

**Comment by purplematter** [comment]
@giodelgado All API calls are working correctly for me but getting a 404 for the bootstrap file (https://bootswatch.com/simplex/bootstrap.min.css).

**Comment by sfofthings** [comment]
@purplematter try using this CDN instead https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/simplex/bootstrap.min.css

**Pull request merged**
